-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibbonacci 0 = 0
fibbonacci 1 = 1
fibbonacci x = fibbonacci (x - 1) + fibbonacci (x - 2)

isEven :: (Integral a) => a -> Bool
isEven a
  | mod a 2 == 0 = True
  | otherwise = False

main :: IO ()
main =
  putStrLn $ show $ sum $ filter isEven $ takeWhile (<4000000) $ map fibbonacci [1..]
